import * as fs from 'fs';
import * as path from 'path';
import { ReviewReport } from '../types';

export class FileFormatter {
  format(report: ReviewReport, outputPath: string): void {
    const content = this.buildMarkdownReport(report);

    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, content, 'utf-8');
    console.log(`Review report saved to: ${outputPath}`);
  }

  private buildMarkdownReport(report: ReviewReport): string {
    let md = `# 🤖 AI PR Code Review Report\n\n`;
    md += `**Repository:** ${report.repository}  \n`;
    md += `**PR Number:** #${report.prNumber}  \n`;
    md += `**Overall Score:** ${report.overallScore}/10  \n`;
    md += `**Date:** ${new Date().toISOString().split('T')[0]}  \n\n`;

    md += `---\n\n`;

    md += `## 📋 Summary\n\n`;
    md += `${report.summary}\n\n`;

    md += `---\n\n`;

    // Critical Issues
    md += `## 🚨 Critical Issues\n\n`;
    if (report.critical.length > 0) {
      md += `> **Must be fixed before merge**\n\n`;
      report.critical.forEach((issue, index) => {
        md += `### ${index + 1}. \`${issue.file}${issue.line ? `:${issue.line}` : ''}\`\n\n`;
        md += `${issue.body}\n\n`;
      });
    } else {
      md += `✅ No critical issues found\n\n`;
    }

    md += `---\n\n`;

    // Warnings
    md += `## ⚠️ Warnings\n\n`;
    if (report.warnings.length > 0) {
      md += `> **Should be addressed**\n\n`;
      report.warnings.forEach((warning, index) => {
        md += `### ${index + 1}. \`${warning.file}${warning.line ? `:${warning.line}` : ''}\`\n\n`;
        md += `${warning.body}\n\n`;
      });
    } else {
      md += `✅ No warnings found\n\n`;
    }

    md += `---\n\n`;

    // Good Practices
    md += `## ✅ Good Practices\n\n`;
    if (report.good.length > 0) {
      report.good.forEach((item) => {
        md += `- ${item}\n`;
      });
      md += `\n`;
    } else {
      md += `No specific highlights\n\n`;
    }

    md += `---\n\n`;
    md += `*Generated by AI PR Reviewer*\n`;

    return md;
  }
}
