import * as fs from 'fs';
import * as path from 'path';
import { ReviewReport } from '../types';

export class FileFormatter {
  format(report: ReviewReport, outputPath: string): void {
    const content = this.buildMarkdownReport(report);

    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, content, 'utf-8');
    console.log(`Review report saved to: ${outputPath}`);
  }

  private buildMarkdownReport(report: ReviewReport): string {
    let md = `# AI PR Code Review Report\n\n`;
    md += `**Repository:** ${report.repository}  \n`;
    md += `**PR Number:** #${report.prNumber}  \n`;
    md += `**Overall Score:** ${report.overallScore}/10  \n`;
    md += `**Date:** ${new Date().toISOString().split('T')[0]}  \n\n`;

    md += `---\n\n`;

    md += `## Summary\n\n`;
    md += `${report.summary}\n\n`;

    if (report.strengths.length > 0) {
      md += `## ✅ Strengths\n\n`;
      report.strengths.forEach((strength) => {
        md += `- ${strength}\n`;
      });
      md += `\n`;
    }

    if (report.concerns.length > 0) {
      md += `## ⚠️ Concerns\n\n`;
      report.concerns.forEach((concern) => {
        md += `- ${concern}\n`;
      });
      md += `\n`;
    }

    if (report.recommendations.length > 0) {
      md += `## 💡 Recommendations\n\n`;
      report.recommendations.forEach((rec) => {
        md += `- ${rec}\n`;
      });
      md += `\n`;
    }

    if (report.comments.length > 0) {
      md += `## 📝 Detailed Comments\n\n`;
      report.comments.forEach((comment, index) => {
        md += `### ${index + 1}. ${comment.file}\n\n`;
        md += `**Severity:** \`${comment.severity}\`  \n`;
        if (comment.line) {
          md += `**Line:** ${comment.line}  \n`;
        }
        md += `\n${comment.body}\n\n`;
      });
    }

    md += `---\n\n`;
    md += `*Generated by AI PR Reviewer*\n`;

    return md;
  }
}
