import { GitHubService } from '../services';
import { ReviewReport } from '../types';

export class GitHubFormatter {
  constructor(private githubService: GitHubService) {}

  async format(report: ReviewReport): Promise<void> {
    const [owner, repo] = report.repository.split('/');

    const summaryComment = this.buildSummaryComment(report);
    await this.githubService.postReviewSummary(owner, repo, report.prNumber, summaryComment);

    const fileComments = report.comments
      .filter((comment) => comment.line)
      .map((comment) => ({
        body: `**[${comment.severity.toUpperCase()}]** ${comment.body}`,
        path: comment.file,
        line: comment.line,
      }));

    if (fileComments.length > 0) {
      await this.githubService.postReviewComments(owner, repo, report.prNumber, fileComments);
    }

    console.log('Review comments posted to GitHub PR');
  }

  private buildSummaryComment(report: ReviewReport): string {
    let comment = `## 🤖 AI Code Review\n\n`;
    comment += `**Overall Score:** ${report.overallScore}/10\n\n`;

    comment += `### Summary\n${report.summary}\n\n`;

    if (report.strengths.length > 0) {
      comment += `### ✅ Strengths\n`;
      report.strengths.forEach((strength) => {
        comment += `- ${strength}\n`;
      });
      comment += `\n`;
    }

    if (report.concerns.length > 0) {
      comment += `### ⚠️ Concerns\n`;
      report.concerns.forEach((concern) => {
        comment += `- ${concern}\n`;
      });
      comment += `\n`;
    }

    if (report.recommendations.length > 0) {
      comment += `### 💡 Recommendations\n`;
      report.recommendations.forEach((rec) => {
        comment += `- ${rec}\n`;
      });
      comment += `\n`;
    }

    comment += `\n---\n*Generated by AI PR Reviewer*`;

    return comment;
  }
}
